# Publish a static transform to center coordinate frame in Rviz
apiVersion: batch/v1
kind: Job
metadata:
  name: static-transform-job
spec:
  template:
    metadata:
      labels:
        app: static-transform
    spec:
      containers:
      - name: static-transform-publisher
        image: 45.33.119.237:5000/ros
        imagePullPolicy: Always
        command: ["/opt/ros/melodic/bin/rosrun"]
        args: ["tf2_ros", "static_transform_publisher", "5", "5", "0", "0", "0", "0", "map", "rviz_offset"]
        env:
          - name: ROS_MASTER_URI
            value: http://45.33.119.237:30001
          - name: ROS_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
      restartPolicy: Never