TrajectoryPlannerROS:
  max_vel_x: 2.0
  min_vel_x: -2.0 # Allowing velocities too low will will stop the obstacle avoidance because low velocities won't actually be high enough to move the robot
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4

  acc_lim_theta: 1.0
  acc_lim_x: 1.0
  acc_lim_y: 0.0

  holonomic_robot: false

  # Goal Tolerance Parameters
  yaw_goal_tolerance: 10  # in rads
  xy_goal_tolerance: 0.5  # in meters
  latch_xy_goal_tolerance: false