local_costmap:
  global_frame: map
  robot_base_frame: base_link
  rolling_window: true #this follows a robot while navigating?
  width: 3.0
  height: 3.0
  resolution: 0.05
  origin_x: 0
  origin_y: 0
