# Run roscore and publish the port using a NodePort
apiVersion: v1
kind: Service
metadata:
  name: roscore-svc
spec:
  type: NodePort   # by using NodePort, the service is published to outside world.
  selector:
    app: roscore     # used to match the pod(s) that run the actual matinv server
  ports:
    - name: roscore-svc-port   # not needed, but I have added this
      protocol: TCP     # this is default (so not needed either)
      port: 11311   # the port used by the server inside the pod/container
      targetPort: 11311   # not sure if we need this because if not specified, it is same as port
      nodePort: 30001  # this is what will be externally published
---
apiVersion: batch/v1
kind: Job
metadata:
  name: roscore-job
spec:
  template:
    metadata:
      labels:
        app: roscore
    spec:
      containers:
      - name: ros-master
        image: 45.33.119.237:5000/ros
        imagePullPolicy: Always
        command: ["/opt/ros/melodic/bin/roscore"]
        args: []
        env:
          - name: ROS_MASTER_URI
            value: http://localhost:11311
          - name: ROS_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
      restartPolicy: Never 