apiVersion: batch/v1
kind: Job
metadata:
  name: simulation-job
spec:
  template:
    metadata:
      labels:
        app: simulation
    spec:
      containers:
      # Run the simulation
      - name: simulation
        image: 45.33.119.237:5000/ros
        imagePullPolicy: Always
        command: ["/opt/ros/melodic/bin/rosrun"]
        args: ["ducksim", "ducksim_node.py", "_num_balls:=50"]
        env:
          - name: ROS_MASTER_URI
            value: http://45.33.119.237:30001
          - name: ROS_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
      restartPolicy: Never